### ISSUE TITLE
Can't get to working on ubuntu

### ISSUE THREAD

**Issue by imbeard** [acseo/docker-cocorico#8]
Hi there,
i'm trying to set up your project on Digital Ocean tried on both Ubuntu 14.04 and 16.04 , container cocorico-web doesn't start due to this error:

AH00526: Syntax error on line 42 of /etc/apache2/apache2.conf:
cocorico-web  | DocumentRoot must be a directory

any clue on how to resolve this?
thanks!

**Comment by npotier** [comment]
Hi @imbeard , the [apache2.conf](https://github.com/acseo/docker-cocorico/blob/master/apache2.conf#L42) file at line 42 indicates the `DocumentRoot` folder, wich is `/var/www/html` 

In the Docker container, `/var/www/html` is a **volume** declared in the [docker-compose.yml](https://github.com/acseo/docker-cocorico/blob/master/docker-compose.yml), line 36. 
On your host machine, it's the **cocorico** folder.

On your host machine, are you sure to have this folder ? You can fetch it by cloning the repo : 

```bash
git clone https://github.com/Cocolabs-SAS/cocorico.git
```

Hope this helps.

**Comment by imbeard** [comment]
Thanks @npotier i've had the cocorico folder in the wrong place

**Comment by frankyadam** [comment]
Hello @npotier @imbeard 

I have the same problem as @imbeard but I don't know where to store the cocorico folder cloned on GitHub...
Do i have to put it inside docker-cocorico folder ? Or aside in the same folder ? Or anywhere else ?

Thank you in advance for your help! 

François
